### ISSUE TITLE
0219 실습

### ISSUE THREAD

**Issue by Jaelinny** [Jaelinny/jelly-blog#14]
- [x] 로컬의 docker 이미지, 컨테이너를 모두 지움
![image](https://github.com/Jaelinny/jelly-blog/assets/148875683/1b7fd811-eba0-4567-ae68-e9c505c98e7a)

- [x] 본인 블로그를 hub.docker 에 push
```
$ sudo docker build -t taengguu/auto-lb:0.1.0 .
$ sudo docker push taengguu/auto-lb:0.1.0
The push refers to repository [docker.io/taengguu/auto-lb]
68e50b78a814: Pushed
c21bee363d32: Pushed
b05bf7593243: Pushed
3186db24a04f: Pushed
e9e54173d788: Pushed
fccdbd3f4153: Pushed
041ae49dfaa3: Pushed
939fce180f82: Pushed
af77b504c612: Pushed
d101c9453715: Mounted from library/ubuntu
0.1.0: digest: sha256:f5c2ed410cd8c5a030487fededa9b790c183e13b637844afb7654ab7238f990c size: 2416

```
![image](https://github.com/Jaelinny/jelly-blog/assets/148875683/3ead5fff-6522-4851-aa1f-f262117d0ca7)
```
$ sudo docker build -t taengguu/auto-lb:0.1.0 -f Dockerfile .
$ sudo docker run -d --name taengguu -p 7070:80 taengguu/auto-lb:0.1.0
$ sudo docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED         STATUS         PORTS                                   NAMES
90d3a77db267   taengguu/auto-lb:0.1.0   "/bin/sh -c 'service…"   4 seconds ago   Up 3 seconds   0.0.0.0:7070->80/tcp, :::7070->80/tcp   taengguu
```
- [x] https://github.com/beyond-sw-camp/be01-101/issues/43 의 compose.yml 파일의 blog 부분에 이미지 주소를 넣음
```
$ cat compose.yml

version: '3.8'
name: awsgoo
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy # https://github.com/nginx-proxy/nginx-proxy
    ports:
      - "9889:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - blog
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 30M

  blog:
    # build: ../../docker_file/httpd
    image: taengguu/auto-lb:0.1.0
    deploy:
      mode: replicated
      replicas: 1 # https://docs.docker.com/compose/compose-file/deploy/#replicas
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=aws.google.com
      - VIRTUAL_PORT=80
```
- [x] 아래 명령어로 가동 ( 경로는 맞출 필요가 있음) -> 경로 변경하여 실행
$ docker compose -f compose/auto_lb/compose.yml  up -d --build --force-recreate

```
$ docker compose -f compose.yml  up -d --build --force-recreate
[+] Running 14/14
 ✔ nginx-proxy 13 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                    9.2s
   ✔ e1caac4eb9d2 Already exists                                                                                   0.0s
   ✔ 88f6f236f401 Pull complete                                                                                    2.3s
   ✔ c3ea3344e711 Pull complete                                                                                    0.8s
   ✔ cc1bb4345a3a Pull complete                                                                                    0.8s
   ✔ da8fa4352481 Pull complete                                                                                    1.6s
   ✔ c7f80e9cdab2 Pull complete                                                                                    2.6s
   ✔ 18a869624cb6 Pull complete                                                                                    2.3s
   ✔ 66ab28d11695 Pull complete                                                                                    3.0s
   ✔ 79b57e45edb0 Pull complete                                                                                    3.2s
   ✔ 2be787a40ace Pull complete                                                                                    3.6s
   ✔ 563a441cec03 Pull complete                                                                                    3.8s
   ✔ 4994460aae36 Pull complete                                                                                    3.9s
   ✔ 4f4fb700ef54 Pull complete                                                                                    4.3s
[+] Running 2/3
 ⠴ Network awsgoo_default          Created                                                                         2.5s
 ✔ Container awsgoo-blog-1         Started                                                                         2.0s
 ✔ Container awsgoo-nginx-proxy-1  Started                                                                         0.9s
```
- [x] 우리가 알고있는 DOCKER CLI 명령어를 통해 컨테이너, 이미지 상태확인
```
$  sudo docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED              STATUS              PORTS                                   NAMES
dd30a0bf9915   nginxproxy/nginx-proxy   "/app/docker-entrypo…"   About a minute ago   Up About a minute   0.0.0.0:9889->80/tcp, :::9889->80/tcp   awsgoo-nginx-proxy-1
df8fdb7d7e67   taengguu/auto-lb:0.1.0   "/bin/sh -c 'service…"   About a minute ago   Up About a minute   80/tcp                                  awsgoo-blog-1
90d3a77db267   taengguu/auto-lb:0.1.0   "/bin/sh -c 'service…"   20 minutes ago       Up 20 minutes       0.0.0.0:7070->80/tcp, :::7070->80/tcp   taengguu

$ sudo docker images
REPOSITORY               TAG       IMAGE ID       CREATED          SIZE
jelly                    123       03fb1041108a   35 minutes ago   462MB
taengguu/auto-lb         0.1.0     03fb1041108a   35 minutes ago   462MB
nginxproxy/nginx-proxy   latest    1a3960925c12   3 hours ago      204MB
```

## ++
- C:\Windows\System32\drivers\etc 관리자 권한으로 메모장 실행
++  127.0.0.1	aws.google.com 추가하기.

## 결과화면
- http://aws.google.com:9889/

![image](https://github.com/Jaelinny/jelly-blog/assets/148875683/cebf988a-700e-4cd0-814f-c2d783b9d42a)

**Comment by Jaelinny** [comment]
compose.yml 파일 수정
```
 version: '3.8'
name: awsgoo
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy # https://github.com/nginx-proxy/nginx-proxy
    ports:
      - "9889:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - blog
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 30M

  blog:
    # build: ../../docker_file/httpd
    image: taengguu/auto-lb:0.1.0
     deploy:
      mode: replicated
      replicas: 1 # https://docs.docker.com/compose/compose-file/deploy/#replicas
      resources: # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
        limits:
          cpus: '0.05'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 20M
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=aws.google.com
      - VIRTUAL_PORT=80
```

**Comment by Afresh2** [comment]
![LGTM](https://i.lgtm.fun/2pd6.gif)

**Comment by parc02** [comment]
![LGTM](https://i.lgtm.fun/2pf2.png)

**Comment by Jaelinny** [comment]
- compose.yml 파일 수정본(위의 compose.yml 코드로 해도 무방)

```
version: '3.8'
name: awsgoo
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy # https://github.com/nginx-proxy/nginx-proxy
    ports:
      - "9889:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - blog
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 30M
  blog:
    image: taengguu/auto-lb:0.1.0
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.05'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 20M
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=aws.google.com
      - VIRTUAL_PORT=80
```
